-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKOItPSnLso5QWx7y
Dso7q2cylIECTII/QylwmRNdAz+gCgYIKoZIzj0DAQehRANCAARDNJvLrBGWPtV8
lizkArkOAbK9xoF2hm+8yGayvceKxs491kjTk8ZAqqfglX/ZcdCDIzsKMODevqlJ
M4JwXnPl
-----END PRIVATE KEY-----